print("Let's play MadLibs for Homework 1")
print("Type one word responses to the following:")

proper_name  = input('proper_name ==> ')
print(proper_name)
adjective1   = input('adjective ==> ')
print(adjective1)
noun1        = input('noun ==> ')
print(noun1)
verb1        = input('verb ==> ')
print(verb1)
noun2        = input('noun ==> ')
print(noun2)
emotion1     = input('emotion ==> ')
print(emotion1)
verb2        = input('verb ==> ')
print(verb2)
noun3        = input('noun ==> ')
print(noun3)
noun4        = input('noun ==> ')
print(noun4)
season       = input('season ==> ')
print(season)
emotion2     = input('emotion ==> ')
print(emotion2)
team_name    = input('team-name ==> ')
print(team_name)
adjective2   = input('adjective ==> ')
print(adjective2)
print("\nHere is your Mad Lib...\n")

print('Hello', (proper_name+','))
print('  Good morning!  Are you looking forward to a/an' ,adjective1, noun1+'?')
print('  You will', verb1, 'a lot of', noun2, 'and feel', emotion1, 'when you do.')
print('  If you do not, you will',verb2,'this', (noun3+'.'))
print()
print('  Did you watch the', noun4, 'this', (season+'?'))
print('  Were you', emotion2, 'when the', team_name, 'won?')
print('  Have a/an', adjective2, 'day!')